// types\loan-application.ts
import { LoanChecklistDocument } from "@/lib/loan-application/server";

export type SelectOption = {
  id: string;
  name: string;
  email?: string | null;
  code?: string | null;
};
export type LoanBankApplication = {
  id: string;
  bank?: string | null;
  branch?: string | null;
  applicationNo?: string | null;
  loginDate?: string | null;
  appliedAmount?: number | null;
  sanctionedAmount?: number | null;
  sanctionDate?: string | null;
  disbursedAmount?: number | null;
  disbursementDate?: string | null;
  roi?: number | null;
  tenure?: number | null;
  status?: string | null;
  remarks?: string | null;
};
export type LoanCoApplicant = {
  id: string;
  name?: string | null;
  relationship?: string | null;
  mobile?: string | null;
  email?: string | null;
  occupation?: string | null;
  income?: number | null;
  cibilScore?: number | null;
};
export type LoanFollowUp = {
  id: string;
  type?: string | null;
  note?: string | null;
  followUpDate?: string | null;
  nextFollowUp?: string | null;
  createdAt?: string | null;
};
export type LoanActivity = {
  id: string;
  type?: string | null;
  title?: string | null;
  description?: string | null;
  createdAt?: string | null;
};
export type LoanDocument = {
  id: string;
  documentCode: string;
  documentType: string;
  originalFileName: string;
  storedFileName: string;
  fileUrl: string;
  mimeType: string;
  fileSize: number;
  remarks?: string | null;
  uploadedAt?: string | null;
};
export type LoanDocumentChecklistItem = {
  code: string;
  name: string;
  required?: boolean;
  isOptional?: boolean;
  isComplete?: boolean;
  documents: LoanChecklistDocument[]
};
export type LoanApplication = {
  id: string;
  applicationId: string;
  fullName: string;
  mobile: string;
  altMobile?: string | null;
  email: string;
  dob?: string | null;
  gender?: string | null;
  maritalStatus?: string | null;
  aadhaar?: string | null;
  pan?: string | null;
  passport?: string | null;
  passportExpireDate?: string | null;
  currentAddress?: string | null;
  permanentAddress?: string | null;
  city?: string | null;
  state?: string | null;
  pin?: string | null;
  enquiryDate?: string | null;
  leadSource?: string | null;
  branchId: string;
  branchName?: string | null;
  counselorId?: string | null;
  counselorName?: string | null;
  fintechAssigneeId?: string | null;
  fintechAssigneeName?: string | null;
  priority?: string | null;
  nextFollowUp?: string | null;
  remarks?: string | null;
  applicantCategory: string;
  loanCategory: string;
  loanStatus: string;
  qualification?: string | null;
  graduationStatus?: string | null;
  percentage?: string | null;
  yearOfPassing?: string | null;
  currentInstitution?: string | null;
  workExperience?: string | null;
  company?: string | null;
  designation?: string | null;
  employmentType?: string | null;
  employeeId?: string | null;
  totalExperience?: string | null;
  currentCompanyExperience?: string | null;
  monthlySalary?: number | null;
  annualIncome?: number | null;
  existingEmi?: number | null;
  employerAddress?: string | null;
  businessName?: string | null;
  businessType?: string | null;
  registrationType?: string | null;
  registrationNumber?: string | null;
  yearsInBusiness?: string | null;
  annualTurnover?: number | null;
  businessAddress?: string | null;
  studyDestination?: string | null;
  country?: string | null;
  university?: string | null;
  courseName?: string | null;
  courseLevel?: string | null;
  courseDuration?: string | null;
  intake?: string | null;
  admissionStatus?: string | null;
  offerLetterReceived?: string | null;
  tuitionFee?: number | null;
  livingExpenses?: number | null;
  otherExpenses?: number | null;
  totalCourseCost?: number | null;
  ownContribution?: number | null;
  requiredLoanAmount?: number | null;
  loanPreference?: string | null;
  collateralAvailable?: string | null;
  loanPurpose?: string | null;
  preferredTenure?: number | null;
  cibilScore?: number | null;
  propertyType?: string | null;
  propertyLocation?: string | null;
  propertyValue?: number | null;
  downPayment?: number | null;
  sanctionedAmount?: number | null;
  disbursedAmount?: number | null;
  depositAmount?: number | null;
  depositDate?: string | null;
  depositReference?: string | null;
  depositBank?: string | null;
  depositRemarks?: string | null;
  bankApplications?: LoanBankApplication[];
  coApplicants?: LoanCoApplicant[];
  followUps?: LoanFollowUp[];
  activities?: LoanActivity[];
  documents?: LoanDocument[];
  createdAt?: string | null;
  updatedAt?: string | null;
};
export type LoanApplicationListFilters = {
  q?: string;
  applicantCategory?: string;
  loanCategory?: string;
  loanStatus?: string;
  fintechAssigneeId?: string;
  bank?: string;
};
