import type { ElementType, ReactNode } from "react";
export function StatusBadge({ status, className = "" }: { status: string; className?: string }) { return <span className={`inline-flex whitespace-nowrap rounded-full border px-3 py-1 text-[10px] font-black uppercase tracking-wider ${className}`}>{status}</span>; }
export function TabHeader({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: ReactNode }) { return <div className="flex items-center justify-between border-b border-inherit pb-3"><div>{eyebrow && <p className="text-[10px] font-black uppercase tracking-widest text-slate-400">{eyebrow}</p>}<h4 className="text-sm font-black text-slate-800 dark:text-slate-100">{title}</h4></div>{action}</div>; }
export function InfoCard({ icon: Icon, label, value }: { icon: ElementType; label: string; value?: ReactNode }) { return <div className="flex items-center gap-3 rounded-2xl border border-slate-100 bg-slate-50 p-3.5 dark:border-slate-800 dark:bg-slate-950"><div className="rounded-xl bg-red-600/10 p-2 text-red-600"><Icon className="h-4 w-4" /></div><div className="min-w-0"><span className="mb-0.5 block text-[9px] font-black uppercase tracking-wider text-slate-400">{label}</span><span className="break-words font-mono text-xs font-extrabold text-slate-800 dark:text-slate-100">{value || "Not provided"}</span></div></div>; }
export function InfoGrid({ children }: { children: ReactNode }) { return <div className="grid grid-cols-1 gap-4 md:grid-cols-2">{children}</div>; }
export function EmptyState({ message }: { message: string }) { return <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 px-5 py-10 text-center text-sm font-semibold text-slate-500 dark:border-slate-700 dark:bg-slate-950">{message}</div>; }
export function DataTable({ columns, children }: { columns: string[]; children: ReactNode }) { return <div className="overflow-x-auto rounded-2xl border border-slate-200 dark:border-slate-800"><table className="w-full text-sm"><thead><tr className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400 dark:bg-slate-950">{columns.map(c => <th key={c} className="px-4 py-3 text-left font-black">{c}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
export const formatDate = (value?: string | Date | null) => { if (!value) return "Not provided"; const d = new Date(value); return Number.isNaN(d.getTime()) ? "Not provided" : d.toLocaleDateString("en-GB"); };
export const formatINR = (value?: number | null) => typeof value === "number" && !Number.isNaN(value) ? new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value) : "—";
export const loanStatusTone = (status: string) => ({ "New Enquiry":"border-blue-200 bg-blue-50 text-blue-700 dark:border-blue-900 dark:bg-blue-950/40 dark:text-blue-300", "Documents Pending":"border-amber-200 bg-amber-50 text-amber-700 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-300", "Under Review":"border-purple-200 bg-purple-50 text-purple-700 dark:border-purple-900 dark:bg-purple-950/40 dark:text-purple-300", "Sanctioned":"border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-300", "Disbursed":"border-green-200 bg-green-50 text-green-700 dark:border-green-900 dark:bg-green-950/40 dark:text-green-300", "Deposit Received":"border-cyan-200 bg-cyan-50 text-cyan-700 dark:border-cyan-900 dark:bg-cyan-950/40 dark:text-cyan-300", "Rejected":"border-red-200 bg-red-50 text-red-700 dark:border-red-900 dark:bg-red-950/40 dark:text-red-300" }[status] ?? "border-slate-200 bg-slate-50 text-slate-600 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300");
